docker/Dockerfile, docker/Dockerfile.local, docker/README.md, docker/docker-build.sh
ROS dependencies are now required to be added to docker/Dockerfile
=> Fixed issue causing docker build to fail in WSL

hardware_interface/README.md, hardware_interface/hardware_interface.ino
=> Ros interface teensy

camera_tracking/launch/multi_camera.launch
daniel doesn't know how to open a PR on his phone.
=> Fexed multi_caerma.lanch adn i hate this keyboard

rocket_league_drl/launch/cartpole.launch, rocket_league_drl/nodes/cart_pole_node, rocket_league_drl/nodes/plotter, rocket_league_drl/params/dqn.yaml, rocket_league_drl/scripts/run_drl.py, rocket_league_drl/src/rocket_league_drl/agents/_agent_interface.py, rocket_league_drl/src/rocket_league_drl/agents/dqn_agent.py, rocket_league_drl/src/rocket_league_drl/interfaces/__init__.py, rocket_league_drl/src/rocket_league_drl/interfaces/cartpole_direct_interface.py, rocket_league_drl/src/rocket_league_drl/interfaces/cartpole_interface.py, rocket_league_drl/src/rocket_league_drl/make_evaluator.py, rocket_league_drl/src/rocket_league_drl/make_trainer.py
Cartpole interface comparisons work well and seem to validate the ROS interface. Further work needs to be done to determine what exactly in a007d16 fixed the problem.
Work to improve plotter should have been done on separate branch.
=> Reuben updates

racersim/README.md
Adrian originally added this doc to the wiki, but given its level of detail, it's better suited here.
This is connected to the push to make the wiki more 'functionally detailed' versus 'technically detailed'.
=> Added adrian's notes

docker/docker-build-base.sh, docker/docker-build.sh, docker/docker-run.sh
make things work on both Ubuntu and Mac
=> make mac compatible

camera_tracking/CMakeLists.txt, camera_tracking/package.xml, docker/Dockerfile, docker/Dockerfile.local, docker/docker-build-base.sh, docker/docker-build.sh, docker/docker-join.sh, docker/docker-run.sh, docker/files/.zshrc
- Changed dockerhub repo image to original image
- Enabled pytorch CUDA support on amd64 platforms
- Fixed alias issue in zsh, rossrc now sources ~/catkin_ws/devel/setup.zsh
=> Docker fixes

local_planner/nodes/simple_drive_node, local_planner/nodes/trajectory_planner_node, local_planner/nodes/waypoint_controller_node, local_planner/setup.py, local_planner/src/local_planner/convert.py, local_planner/src/local_planner/pure_pursuit.py, racersim/nodes/racersim_node, racersim/setup.py, racersim/src/racersim/__init__.py, racersim/src/racersim/ball.py, racersim/src/racersim/car.py, racersim/src/racersim/goal.py, racersim/src/racersim/renderer.py, racersim/src/racersim/sim.py, racersim/src/racersim/tire.py, racersim/src/racersim/world.py, rocket_league_highlevel/nodes/simple_hardcoded, rocket_league_highlevel/setup.py
was working locally after these changes. might be more to change, haven't investigated.
=> fixed noetic upgrade issues

rocket_league_drl/launch/snake.launch, rocket_league_drl/nodes/plotter, rocket_league_drl/params/snake.yaml, rocket_league_drl/src/rocket_league_drl/_ros_interface.py, rocket_league_drl/src/rocket_league_drl/snake_interface.py
Integrate into the existing plotter code.
=> plotter for autonomy data

rocket_league_drl/launch/cartpole.launch, rocket_league_drl/nodes/plotter
=> Autonomy cleanup

camera_tracking/CMakeLists.txt, camera_tracking/config/apriltag_settings.yaml, camera_tracking/config/tags.yaml, camera_tracking/include/camera_tracking/localizer.h, camera_tracking/launch/camera_boilerplate.launch, camera_tracking/launch/position_smoother.launch, camera_tracking/nodes/position_smoother, camera_tracking/package.xml, camera_tracking/src/localizer.cpp, camera_tracking/src/localizer_node.cpp, docker/Dockerfile, docker/Dockerfile.local, docker/docker-build-base.sh, rocket_league_launch/launch/c3po.launch, rocket_league_launch/launch/r2d2.launch, rocket_league_launch/launch/test_pereception.launch
- Added smoothing to the camera's position (with magic).
- Still outputs transforms in 3d though, next goal is to transform into 2d.
- Seems to be slightly smoother between cameras
- Added Eigen as a dependency for Linear Algebra magic (PR is mainly to trigger the autobuild for the integration test)
=> TF breakup + Magic

rktl_launch/config/rocket_league_params.yaml, rktl_sim/nodes/simulator_node, rktl_sim/urdf/backwall.urdf, rktl_sim/urdf/goal.urdf, rktl_sim/urdf/sidewall.urdf
=> modified field size

rktl_autonomy/src/rktl_autonomy/rocket_league_interface.py, rktl_msgs/CMakeLists.txt, rktl_msgs/msg/ControlEffort.msg, rktl_sim/nodes/keyboard_interface, rktl_sim/nodes/simulator_node, rktl_sim/nodes/xbox_interface
creates a custom message type for effort. Also switches from 32 bit float to 64 bit double. It gets widened when output from the neural network. I previously thought the teensy couldn't do double math, but it can.
Notes: This breaks the Arduino interface, but @jaketockerman is refactoring that anyways. It also breaks the sim test cases, but @hmccarty is refactoring those. It also breaks the mid level software, but that is already broken.
=> Effort msg

rktl_launch/rviz/field.rviz, rktl_perception/config/cam0/pointgrey.yaml, rktl_perception/config/cam1/pointgrey.yaml, rktl_perception/config/cam2/pointgrey.yaml, rktl_perception/config/cam3/pointgrey.yaml
=> Integration

rktl_perception/launch/camera.launch, rktl_perception/src/ball_detection_node.cpp, rktl_perception/src/localizer.cpp
it was daniel's fault
(he didn't scale the vector)
=> Ball tracking

docker/README.md, docker/docker-build.sh, docker/docker-join.sh, docker/docker-run.sh, docker/docker-server-run.sh
use --net=host on server and ssh -Y to pass x11 forwarding over ssh
=> Remote x11 forwarding

rktl_perception/config/ball_settings.yaml, rktl_perception/include/rktl_perception/ball_detection_node.h, rktl_perception/src/ball_detection_node.cpp
=> added erosion and dilation to YAML

rktl_autonomy/README.md, rktl_autonomy/config/rocket_league.yaml, rktl_autonomy/scripts/eval_rocket_league.py
This is the script I used to make those Excel plots. All detail to run is in README.
=> Eval script

rktl_game/launch/game.launch, rktl_game/nodes/game_manager, rktl_game/web/index.js
=> Undoing garbage

rktl_control/config/pose_synchronizer.yaml, rktl_control/nodes/pose_synchronizer
This lets us plot latency real time so we can tune perception more easily
=> add ability to plot latency real time

rktl_planner/config/patrol_planner.yaml, rktl_planner/nodes/patrol_planner
Some possible improvements to the patrol planner. Seem pretty good in sim but need to be tested IRL.
=> Patrol improve

rktl_autonomy/scripts/modular_train.py, rktl_autonomy/src/rktl_autonomy/__init__.py
Fixes modular training. Can someone test on Windows? The paths here didn't work at first.
=> Modular training fixes

rktl_autonomy/config/rocket_league.yaml, rktl_autonomy/scripts/train_rocket_league.py, rktl_autonomy/src/rktl_autonomy/rocket_league_interface.py
- Add reward for velocity sign change
- Add loading from previous weights (thanks @rtjord)
=> Add dir change reward and previous weights loading

rktl_sim/src/simulator/car.py
Fixed testcase on github by converting a float to a float32
=> changed float to float32
